server:
  #端口号
  port: 8001


spring:
  application:
    #服务名称
    name: cloud-payment-service
  datasource:
    #当前数据库操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    #mysql数据库地址url
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    #数据库用户名
    username: root
    #数据库密码
    password: root
    druid:
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      validation-query: SELECT 1

mybatis:
  #mapper文件的位置,在mapper包下
  mapperLocations: classpath:mappper/*.xml
  #实体类所在的包
  type-aliases-package: com.atguigu.springcloud.entities