server:
  port: 7001

########单机版eureka服务
#eureka:
#  instance:
#    hostname: localhsot #eureka服务端实例名称
#  client:
#    register-with-eureka: false #表示不像注册中心注册自己
#    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不像注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例,并不区检索服务
    service-url:
      #集群
      #defaultZone: http://eureka7002.com:7002/eureka/
      #单机
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护,自我保护功能可以在某个服务出现问题时不会立即删除该服务,而是保存一定的时间(90s),
    #因为它可能是由于网络的原因导致暂时无法获取心跳,如果超过90s后依然无法获取到该服务的心跳,那么就会删除该服务
    #关闭自我保护后,在获取不到某个服务的心跳时,会直接删除该服务
    enable-self-preservation: false
    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
    eviction-interval-timer-in-ms: 2000
