#配置端口
server:
  port: 8004

#配置spring
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      #配置zookeeper的服务地址,将该客户端注册到zookeeper服务端中
      connect-string: 192.168.43.210:2181

